### ISSUE TITLE
BRAF has no Ensembl Gene ID anymore

### ISSUE THREAD

**Issue by floatingpurr** [SuLab/scheduled-bots#21]
Hey guys, I noticed that [BRAF](https://www.wikidata.org/wiki/Q17853226) lost its Ensembl Gene ID. Probably, it was removed on Aug, 16 by ProteinBoxBot. AFAIK [this](https://www.wikidata.org/w/index.php?title=Q17853226&oldid=727229762) is the last item version with the Ensembl ID.

I'm not sure it is normal. It could be a symptom of a more general problem which may compromise mappings/queries based on Ensembl Gene IDs.

**Comment by stuppie** [comment]
Hmm, that's weird. Looking at the logs, it removed the ensembl ID off of 305 (out of ~20k genes). Why? Looking at the IDs of the ones it did this on, it looks like they were among the most recently modified. Possibly the SPARQL endpoint hadn't finished updating and it got conflicting data...  Running bot again and will check them. Thanks
