### ISSUE TITLE
Duplicated Ensembl IDs

### ISSUE THREAD

**Issue by floatingpurr** [SuLab/scheduled-bots#23]
Hi guys! I am opening this issue to notify a potential problem that I found in data.

According to this query:

```sparql
SELECT ?item ?itemLabel ?item2 ?item2Label 
WHERE 
{
  ?item wdt:P594 ?ensg .
  ?item2 wdt:P594 ?ensg .
  FILTER (str(?item) > str(?item2))
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
```
[Try it!](https://query.wikidata.org/#SELECT%20%3Fitem%20%3FitemLabel%20%3Fitem2%20%3Fitem2Label%20%0AWHERE%20%0A%7B%0A%20%20%3Fitem%20wdt%3AP594%20%3Fensg%20.%0A%20%20%3Fitem2%20wdt%3AP594%20%3Fensg%20.%0A%20%20FILTER%20%28str%28%3Fitem%29%20%3E%20str%28%3Fitem2%29%29%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D)

There are some Ensembl IDs re used across items. It sounds pretty strange.

For example, [`Q413766`](https://www.wikidata.org/wiki/Q413766) is Fibronectin 1 protein, and [`Q14819473`](https://www.wikidata.org/wiki/Q14819473) is its encoding gene. Both items share 
`?item wdt:P594 'ENSG00000115414'`. AFAIK, ENSG* should be reserved to genes. 

Is there something to check in data loading process?

PS: guys at SuLab, please don't hate me too much for my issues submissions 😃

**Comment by stuppie** [comment]
No problem Andrea, thanks for pointing these out!
I haven't looked at all the instances, but at least in this case in particular, it looks like it was added by Tobias1984 in 2013 ([link](https://www.wikidata.org/w/index.php?title=Q413766&type=revision&diff=49271077&oldid=29459037)).
Theres 54 cases, so I'm guessing its a combination of merges and old statements.. Will take a look at the others

**Comment by stuppie** [comment]
Looks like some of the others are cases in which a gene has two different Entrez IDs but Ensembl calls it the same gene.
Example: https://www.wikidata.org/wiki/Q21821399  https://www.wikidata.org/wiki/Q27107877

**Comment by floatingpurr** [comment]
I see. The latter is the same case of https://github.com/SuLab/scheduled-bots/issues/19

Regarding Fibronectin-_like_ cases, namely _proteins with an ENSG*_, I tried the get them all with the following query:

```sparql
SELECT distinct ?item ?itemLabel
WHERE 
{
  ?item wdt:P594 ?ensg .
  ?item wdt:P31|wdt:P279 wd:Q8054 .
  FILTER NOT EXISTS {?item wdt:P31|wdt:P279 wd:Q7187}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
```
[Try it!](https://query.wikidata.org/#SELECT%20distinct%20%3Fitem%20%3FitemLabel%0AWHERE%20%0A%7B%0A%20%20%3Fitem%20wdt%3AP594%20%3Fensg%20.%0A%20%20%3Fitem%20wdt%3AP31%7Cwdt%3AP279%20wd%3AQ8054%20.%0A%20%20FILTER%20NOT%20EXISTS%20%7B%3Fitem%20wdt%3AP31%7Cwdt%3AP279%20wd%3AQ7187%7D%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D)

Turned out there are 2 proteins (i.e., [Fibronectin 1](https://www.wikidata.org/wiki/Q413766) and [Myoglobin](https://www.wikidata.org/wiki/Q192642)) with both an ENSG* and an ENSMUS* identifier as Ensembl Gene ID. The user you mentioned inserted those statements in 2013. The solution is removing those 4 statements.

Regarding [CRIP1](https://www.wikidata.org/wiki/Q17909779), someone at `213.96.40.12` [marked](https://www.wikidata.org/w/index.php?title=Q17909779&diff=771239029&oldid=768514576) the item as a protein, but it looks not correct to me, since this is a gene. The solution is removing the statement "instance of protein"

If you agree, I'd proceed as suggested.

**Comment by stuppie** [comment]
Looks good to me, thanks

**Comment by floatingpurr** [comment]
You are welcome!

I've just updated those 3 items. Strangely, this query:

```sparql
SELECT distinct ?item ?itemLabel
WHERE 
{
  ?item wdt:P594 ?ensg .
  ?item wdt:P31|wdt:P279 wd:Q8054 .
  FILTER NOT EXISTS {?item wdt:P31|wdt:P279 wd:Q7187}
  SERVICE wikibase:label { bd:serviceParam wikibase:language "[AUTO_LANGUAGE],en". }
}
```
[Try it!](https://query.wikidata.org/#SELECT%20distinct%20%3Fitem%20%3FitemLabel%0AWHERE%20%0A%7B%0A%20%20%3Fitem%20wdt%3AP594%20%3Fensg%20.%0A%20%20%3Fitem%20wdt%3AP31%7Cwdt%3AP279%20wd%3AQ8054%20.%0A%20%20FILTER%20NOT%20EXISTS%20%7B%3Fitem%20wdt%3AP31%7Cwdt%3AP279%20wd%3AQ7187%7D%0A%20%20SERVICE%20wikibase%3Alabel%20%7B%20bd%3AserviceParam%20wikibase%3Alanguage%20%22%5BAUTO_LANGUAGE%5D%2Cen%22.%20%7D%0A%7D)

still returns old results. Probably something similar to https://github.com/SuLab/scheduled-bots/issues/22 is going on.

I'm going to close this issue and to report the problem with stale data in Phabricator.

Thanks! 🤙
