### ISSUE TITLE
Jenkins/scheduled-bot cleanup needed

### ISSUE THREAD

**Issue by andrawaag** [SuLab/scheduled-bots#55]
Both the microbial and mammalian Genebots are consolidated into a single [bot](https://github.com/SuLab/scheduled-bots/blob/master/scheduled_bots/geneprotein/GeneBot.py).  
Both the geneprotein folder in scheduled-bots and jenkins requires some reordering to make this more visible. 
Also before this consolidation of genebots, multiple bots on mammalian genes, e.g. rat and mouse ran, which don't run now. They need to resume, to maintain the content already added.

**Comment by andrewsu** [comment]
@andrawaag You say that we have "multiple bots on mammalian genes, e.g. rat and mouse ran, which don't run now" but need to be resumed.  But what do those bots do that the single consolidated bot does not?

**Comment by andrawaag** [comment]
They differ on specific properties. e.g. Rat and Mouse gene items are maintained with MGI identifiers. The question is if these should be added to the consolidated bot code, or the bot needs to be rewritten so that there is a core gene library with again distinct code bases per species, where each import the generic gene bot code base

**Comment by andrawaag** [comment]
I am going to close this issue and move to different issues
