### ISSUE TITLE
change detector is running, but updates mails are not sent

### ISSUE THREAD

**Issue by andrawaag** [SuLab/scheduled-bots#57]
The bot that detect changes between WD and DO runs accordingly as the output on [Jenkins suggests](http://jenkins.sulab.org/view/3%20Change%20Detectors/job/DO_Robot/). However, the configured emails are not received. 

<img width="879" alt="afbeelding" src="https://user-images.githubusercontent.com/770306/73968991-daf9c200-491a-11ea-9cc1-e3a9a8e5bff6.png">

**Comment by andrawaag** [comment]
The output suggests that the sending email needs to be verified.
<img width="970" alt="afbeelding" src="https://user-images.githubusercontent.com/770306/73969242-56f40a00-491b-11ea-8fa1-05064929eed5.png">

However it is unclear to me how such an address needs to verified.

**Comment by andrewsu** [comment]
I verified the email address within the AWS console

![image](https://user-images.githubusercontent.com/2635409/73972441-b7605880-48d5-11ea-8d4b-9a178c828e7a.png)

there _may_ also be an issue with the SES "sandbox" (https://serverfault.com/questions/812916/how-to-fix-554-message-rejected-email-address-is-not-verified), but it looks like we are not in sandbox mode (according to https://docs.aws.amazon.com/ses/latest/DeveloperGuide/request-production-access.html).  So, fingers crossed, this should be fixed now.  Triggered the DO Robot to test...

**Comment by andrewsu** [comment]
worked! email received...

**Comment by andrawaag** [comment]
I can also confirm that I received the email. However, it was in the spambox.
